title: 'Emmanuel Christian Church'
default_lang: en
author:
  name: 'Brandon Himes'
  email: joe@test.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Website for Emmanuel Christian Church'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
email: your-email@domain.com
description: 'The website for Emmanuel Christian Church located in the El Cajon community of Harbison Canyon. Come join us this Sunday to celebrate the love of God!'
social:
  -
    label: Twitter
    url: '#'
    icon: twitter
  -
    label: Facebook
    url: '#'
    icon: facebook
  -
    label: Google+
    url: '#'
    icon: google-plus
  -
    label: Github
    url: '#'
    icon: github
  -
    label: Dribbble
    url: '#'
    icon: dribbble
copyright:
  line1: ECC
  line2: 'Design:'
  url: 'https://brandonhimes.com'
  url_label: 'Brandon Himes'
logo:
  text1: Emmanuel
  text2: 'Christian Church'
submenu:
  -
    text: 'Dolore Sed'
    link: '#'
  -
    text: Consequat
    link: '#'
  -
    text: 'Lorem Magna'
    link: '#'
  -
    text: 'Sed Magna'
    link: '#'
  -
    text: 'Ipsum Nisl'
    link: '#'
buttons:
  -
    text: 'Connect'
    link: '#'
